name: Static Checks

on: pull_request

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
  
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install .
      - name: Run mypy
        run: mypy .
      - name: Run ruff
        run: ruff check
      - name: Pytest
        run: pytest -m unit_test
