name: Static Checks

on: pull_request

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
      fail-fast: false
  
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install .
      - name: Run mypy
        run: mypy .
      - name: Run ruff
        run: ruff check
      - name: Pytest
        run: pytest -m unit
